version: '3.8'

services:
  # Main application (backend + frontend)
  materia-v5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: materia-v5
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      - C:/materia:/materia  # Mount the materia directory for password hashes and shared database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  materia_data:
    driver: local
